eternitynewBundle_homepage:
    pattern:  /hello
    defaults: { _controller: eternityNewBundle:Homepage:index }

eternitynewBundle_contact:
    pattern: /contact
    defaults: { _controller: eternityNewBundle:contact:contact }
