parameters:
#    eternity_new.example.class: eternity\NewBundle\Example

services:
#    eternity_new.example:
#        class: %eternity_new.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
