parameters:
#    tutowelcome.example.class: tuto\welcomeBundle\Example

services:
#    tutowelcome.example:
#        class: %tutowelcome.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
